title: Officail Harshavardhan Dwarapu Website
description:  'Harshavardhan Dwarapu is a soft skills trainer, a business owner, and a mentor who works extensively with young aspirants in India, and advocates them on career building, skill development, corporate etiquette, IT career paths, and proficiency in English language.'
show_navigation: true
google_analytics:
theme: jekyll-theme-leap-day
meet_url: "https://1642.3cx.cloud/meet/harsha"
talk_url: "https://1642.3cx.cloud/harsha"
facebook_url: "https://www.facebook.com/profile.php?id=61550812075998"
linkedin_url: "https://www.linkedin.com/in/hdwarapu"